### ISSUE TITLE
"RefResolutionError" exception raised when resolving "$ref" with no prefix (file:///)

### ISSUE THREAD

**Issue by jar3b** [cwacek/python-jsonschema-objects#66]
I have 2 simple json schemas, and second schema contains refs to definitions from first. In my case, all refs looks like:
```
    "person": {
      "description": "Person data and document",
      "$ref": "core.json#/definitions/personDataDocument"
    },
```
i.e. without specify prefix (`python-jsonschema-objects` supports relative file refs only in format like `"$ref": "file:///core.json#/definitions/personDataDocument"`). This can be seen in `__init__.py:83`. For me specifying prefix is not always good (eg if schemas was placed into web server).

**Comment by rafikmatta** [comment]
Has this been resolved? I am still experiencing the issue in the latest build

**Comment by jar3b** [comment]
rafikmatta, it's resolved in my fork. I prepared a PR for this, you can look for it above.

**Comment by rafikmatta** [comment]
Still experiencing same issue with your fork, that's certainly odd.

**Comment by cwacek** [comment]
@rafikmatta Do you have an example that causes this issue? If so, we can write a test against it and make sure we've solved it.

**Comment by dodgyville** [comment]
Hi, I think I have the same or similar problem.

I'm trying to use this excellent library on the multi-file gltf json schema (https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/glTF.schema.json). I've cloned the gltf repo locally and written my code but when I go to create the object builder I get the error:

`jsonschema.exceptions.RefResolutionError: unknown url type: 'glTFProperty.schema.json'`

Drilling down into it, ObjectBuilder is looking for the glTFProperty.schema.json file defined in $ref in the /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/python_jsonschema_objects directory instead of the current working directory. 

`
from python_jsonschema_objects import ObjectBuilder

file_name = "glTF.schema.json"
builder = ObjectBuilder(file_name)
`

**Comment by warner121** [comment]
Taking the example from the json-schema documentation on structuring complex schema: [https://json-schema.org/understanding-json-schema/structuring.html](url).

I create a file **address_pass.json** where address is defined internally:

```
{
  "$schema": "http://json-schema.org/draft-07/schema#",

  "definitions": {
    "address": {
      "type": "object",
      "properties": {
        "street_address": { "type": "string" },
        "city":           { "type": "string" },
        "state":          { "type": "string" }
      },
      "required": ["street_address", "city", "state"]
    }
  },

  "type": "object",

  "properties": {
    "billing_address": { "$ref": "#/definitions/address" },
    "shipping_address": { "$ref": "#/definitions/address" }
  }
}
```
The code below illustrates this validates the example instance:
```python
import json
from jsonschema import validate

instance = {
  "shipping_address": {
    "street_address": "1600 Pennsylvania Avenue NW",
    "city": "Washington",
    "state": "DC"
  },
  "billing_address": {
    "street_address": "1st Street SE",
    "city": "Washington",
    "state": "DC"
  }
}

with open('address_pass.json') as json_data:
    schema = json.load(json_data)
    json_data.close()
    
validate(instance=instance, schema=schema)
```
All good. Now, the example does not define the content of **definitions.json** but I believe it should look like this:
```
{
  "address": {
    "type": "object",
    "properties": {
      "street_address": { "type": "string" },
      "city":           { "type": "string" },
      "state":          { "type": "string" }
    },
    "required": ["street_address", "city", "state"]
  }
}
```
With corresponding reference from within **address_fail.json** as below:
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",

  "definitions": {
    "address": {
      "type": "object",
      "properties": {
        "street_address": { "type": "string" },
        "city":           { "type": "string" },
        "state":          { "type": "string" }
      },
      "required": ["street_address", "city", "state"]
    }
  },

  "type": "object",

  "properties": {
    "billing_address": { "$ref": "definitions.json#/address" },
    "shipping_address": { "$ref": "definitions.json#/address" }
  }
}
```
However, the same code as above now fails with the RefResolutionError reported above:
```python
import json
from jsonschema import validate

instance = {
  "shipping_address": {
    "street_address": "1600 Pennsylvania Avenue NW",
    "city": "Washington",
    "state": "DC"
  },
  "billing_address": {
    "street_address": "1st Street SE",
    "city": "Washington",
    "state": "DC"
  }
}

with open('address_fail.json') as json_data:
    schema = json.load(json_data)
    json_data.close()
    
validate(instance=instance, schema=schema)
```
Furthermore, replacing ```$ref``` with ```file``` and a full path to **definitions.json**  illustrates the external reference does work. So the issue seems to be simply in locating the file.
